backend:
  name: github
  repo: simooooone/simonefoschi.it
  site_domain: simonefoschi.it
  branch: main
media_folder: src/img
public_folder: /static
collections:
  - name: posts
    label: Posts
    folder: /src/posts
    create: true
    fields:
      - { name: title, label: Title, widget: 'string'  }
      - { name: description, label: Description, widget: 'string' }
      - { name: date, label: Date, widget: 'string' }
      - { name: update, label: Update, widget: 'string' }
      - { name: author, label: Author, widget: 'string' }
      - { name: published, label: Published, widget: 'string' }
      - { name: langKey, label: Lang, widget: 'string' }
      - { name: body, label: Body, widget: markdown }
