backend:
  name: github
  repo: simooooone/simonefoschi.it
  site_domain: https://www.simonefoschi.it/
  branch: master
media_folder: src/img
public_folder: /static
collections:
  - name: posts
    label: Posts
    folder: /src/posts
    create: true
    fields:
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: date, label: Date }
      - { name: update, label: Update }
      - { name: author, label: Author }
      - { name: langKey, label: Lang }
      - { name: body, label: Body, widget: markdown }
